[[redirects]]
  from = "/api/*"
  to = "https://35.237.64.235/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "https://api.jamiehughes.info/*"
  to = "https://35.237.64.235/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"